/* istanbul ignore file */

// Auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const MOBILE_AUTH_PENDING = 'MOBILE_AUTH_PENDING';

// Vehicles
export const LOAD_VEHICLES_START = "LOAD_VEHICLES_START";
export const LOAD_VEHICLES_SUCCESS = "LOAD_VEHICLES_SUCCESS";
export const LOAD_VEHICLES_FAIL = "LOAD_VEHICLES_FAIL";
export const SUBSCRIBE_LIVE_VEHICLES_STATUS = "SUBSCRIBE_LIVE_VEHICLES_STATUS";
export const UNSUBSCRIBE_LIVE_VEHICLES_STATUS = "UNSUBSCRIBE_LIVE_VEHICLES_STATUS";
export const NOTIFY_LIVE_VEHICLES_SUBSCRIBERS_SUCCESS = "NOTIFY_LIVE_VEHICLES_SUBSCRIBERS_SUCCESS";
export const NOTIFY_LIVE_VEHICLES_SUBSCRIBERS_FAIL = "NOTIFY_LIVE_VEHICLES_SUBSCRIBERS_FAIL";